server:
  port: 8280
spring:
  application:
    name: zhongzhu-message-listener
  profiles:
    active: dev # 默认为开发环境

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

