server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: zhongzhu-application-server
  profiles:
    active: dev # 默认为开发环境
  servlet:
    multipart:
      enabled: true # 开启文件上传
      max-file-size: 10MB # 限制文件上传大小为10MB

    # mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
# 文档管理 - 访问地址ip:port/doc.html
knife4j:
  enable: true